#!/bin/sh -l
# FILENAME: scv_init

#SBATCH -A standby
#SBATCH --nodes=1 --gpus-per-node=1 --cpus-per-task=8
#SBATCH --time=04:00:00
#SBATCH --job-name ID
#SBATCH --output slurm/%x-%A.out
#SBATCH --constraint="a100|v100"

hostname
nvidia-smi

#export QT_QPA_PLATFORM='offscreen'
#export XDG_RUNTIME_DIR='/home/kim2712/.xdg'

module load learning/conda-2020.11-py38-gpu
module load ml-toolkit-gpu/all/all

exp_dir=`pwd`


#nvidia-smi

xvfb-run python $exp_dir/main.py --exp_dir $exp_dir --n_sample NSP --lr LRS --method MTD #--epoch 2
